### ISSUE TITLE
No image on 480P

### ISSUE THREAD

**Issue by ScottishB** [GameboxSystems/Gamebox-Product-Firmware-Updates#2]
Using the later 2.0.1, no picture on PAL with 480P.

**Comment by GameboxSystems** [comment]
480p is temperamental with some screens but displays fine on others. Extensive testing has been done with various timings and resolutions to improve compatibility which did succeed to some extent. However, there will still be edge cases that are not reconcilable. Closing issue, as of now there is no plan to experiment further with 480p PAL mode.
