### ISSUE TITLE
Intermittent issue with menus in 2.0.1

### ISSUE THREAD

**Issue by ScottishB** [GameboxSystems/Gamebox-Product-Firmware-Updates#3]
Hi,
  When using the menus if I go into display settings and press B to back up it sometimes highlights no option in the menu and requires a reset. 
  
Normally an option is highlighted on pressing B in the main menu but when this happens all options are grey.

**Comment by GameboxSystems** [comment]
This has been fixed in v2.0.2 which has been pushed to the repo. Closing issue.
