### ISSUE TITLE
64HD v2.0.2: Wrong version on "Info" Section.

### ISSUE THREAD

**Issue by ferdraghi** [GameboxSystems/Gamebox-Product-Firmware-Updates#5]
Flashed v2.0.2 on my 64HD and when I went to the Info section to confirm, it displays v1.7.3 with a build date of May 18th. 

I confirmed I downloaded the right version by downloading the actual 1.7.3 file and doing a diff against the file I flashed into my 64HD and they are different. Moreover my 64HD displays a new resolution available: 800p which according to the changelog was added on 2.0.1 (assuming it's referring to 1024x768) so I know I didn't accidentally flashed 1.7.3 on my unit... Not sure if this is a known issue but I wanted to report it just in case.

**Comment by FibreFoX** [comment]
Hm, I have updated from v1.7.3 to v2.0.2, and for me it displays correctly.

**Comment by ferdraghi** [comment]
> Hm, I have updated from v1.7.3 to v2.0.2, and for me it displays correctly.

The weird thing is that I updated from 1.6.something, I never had 1.7.3 on my unit so I have no idea how this could've happened unless the wrong version was set on the file itself.

**Comment by FibreFoX** [comment]
Hm, thats interesting. I had a 1.6.x version on there (not sure if even some earlier version) and updated to 1.7.3, and just recently updated to v2.0.2

Not sure how this all works, maybe try reflashing the 1.7.3 and then 2.0.2 ... maybe something is not properly flashed.

**Comment by FibreFoX** [comment]
@ferdraghi It seems that the version 2.0.2 got "updated" with a different commit:
https://github.com/GameboxSystems/Gamebox-Product-Firmware-Updates/commit/e4e9eeb65be10e28e7f9c607dd329184e43bfc2f

Maybe you got the "broken" one? Can you redownload the file and look if the current file matches your local stored one? (In addition to reflashing)

**Comment by ferdraghi** [comment]
> @ferdraghi It seems that the version 2.0.2 got "updated" with a different commit: [e4e9eeb](https://github.com/GameboxSystems/Gamebox-Product-Firmware-Updates/commit/e4e9eeb65be10e28e7f9c607dd329184e43bfc2f)
> 
> Maybe you got the "broken" one? Can you redownload the file and look if the current file matches your local stored one? (In addition to reflashing)

that one was already up when I updated, I indeed downloaded the correct 2.0.2 file.

**Comment by GameboxSystems** [comment]
Fixed up new firmware files updated. Closing.
